sudo: required
services:
  - docker

before_install:
  - cd project-env/frontend/ && docker build -t silvmike/docker-react -f Dockerfile.dev .

script:
  - docker run silvmike/docker-react npm run test -- --coverage