sudo: required
services:
  - docker

before_install:
  - docker build -t silvmike/docker-react -f project-env/frontend/Dockerfile.dev project-env/frontend/

script:
  - docker run silvmike/docker-react npm run test -- --coverage